################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  debug: true
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.localhost`)"
################################################################
# Traefik Logging
################################################################
log:
  level: INFO

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

################################################################
# Challenge HTTP
################################################################
certificatesResolvers:
  myresolver:
    acme:
      email: serban.paul.91@gmail.com 
      storage: acme.json
      tlsChallenge: true

