name: Shell
on:
  push:
  workflow_call:

jobs:
  lint:
    name: Lint Shell with ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        with:
          path: |
            ./*/*.bash
            ./*/*/*.bash
            ./*/*/*/*.bash
